#!/usr/bin/env python3
"""Pull the VOP3 microcode images out of the PLG150-AN ROM (HD6413002, roms/PLG150-AN_cpuview.bin).

    python tools/extract_plg150an_vop3.py

Writes docs/vop3_an/<name>.bin (raw 8 words per step, FS1R register order below) and docs/vop3_an.md.

From the decompiled driver FUN_0007f87c (Ghidra project PLG150AN, VOP3 at 0x400000, 16-bit registers
at base + 2*reg, same layout as the FS1R's FUN_0000B5E2):
    image = u16 first_step, u16 count, then per step 8 words:
      w0 -> reg 0xC (& 0xF)       byte table
      w1 -> regs 0x1A/0x1C        DRAM address (only if w3 & 7 != 0; VOP3-1 on the FS1R has no DRAM)
      w2 -> reg 0xB               coefficient
      w3 -> reg 10 (& 7)
      w4 -> reg 9
      w5 -> reg 8
      w6 -> reg 7
      w7 -> reg 6
    then, when the flag argument is 1, 15 words to reg 0x16 (per-bus levels, as the FS1R's 0x37861A).
FUN_0007f9e6 applies patch lists (0xC0598, 0xC19D2) on top of the 0xBB9F0 image.
"""
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ROM = ROOT.parent / "FS1R_DISASM/roms/PLG150-AN_cpuview.bin"
OUT = ROOT / "docs/vop3_an"

IMAGES = {   # name: (address, has per-bus levels)   callers: FUN_00080a3a (boot), FUN_0006e62c (mode 0/1/2)
    "boot_blank": (0xBB16E, True),
    "base": (0xBB9F0, True),
    "mode0": (0xBDA12, False),
    "mode1": (0xBE894, False),
    "mode2": (0xBF716, False),
}
COLS = ["r0C", "dram", "r0B", "r10", "r9", "r8", "r7", "r6"]


def read_image(rom, addr):
    first, count = struct.unpack_from(">HH", rom, addr)
    steps = [struct.unpack_from(">8H", rom, addr + 4 + 16 * i) for i in range(count)]
    return first, steps


def main():
    rom = ROM.read_bytes()
    OUT.mkdir(parents=True, exist_ok=True)
    md = ["# PLG150-AN VOP3 microcode\n", "Generated by `tools/extract_plg150an_vop3.py`; format in its docstring.\n"]
    for name, (addr, bus) in IMAGES.items():
        first, steps = read_image(rom, addr)
        assert first + len(steps) <= 512, name
        (OUT / f"{name}.bin").write_bytes(b"".join(struct.pack(">8H", *s) for s in steps))
        md.append(f"\n## {name} (ROM 0x{addr:X}): steps 0x{first:03X}..0x{first+len(steps)-1:03X}, "
                  f"{sum(1 for s in steps if any(s))} non-empty\n")
        if bus:
            lv = struct.unpack_from(">15H", rom, addr + 4 + 16 * len(steps))
            md.append("per-bus levels (reg 0x16): " + " ".join("%04X" % v for v in lv) + "\n")
        md.append("\n| step | " + " | ".join(COLS) + " |\n|" + "---|" * 9 + "\n")
        for i, s in enumerate(steps):
            if any(s):
                md.append(f"| {first+i:03X} | " + " | ".join("%04X" % w for w in s) + " |\n")
    (ROOT / "docs/vop3_an.md").write_text("".join(md))
    print("wrote", OUT, "and docs/vop3_an.md")


if __name__ == "__main__":
    main()
