# hollow_embed_skin(<skin dir> <out.cpp>): at build time, turns every file under the skin folder into
# a byte array in <out.cpp>, which defines hollow::kSkinFiles and kSkinFileCount (src/embedded_skin.h).
# The file is regenerated when any skin file changes; adding or removing files re-runs the configure
# step. A missing or empty folder gives an empty table.
#
# hollow_embed_files(<out.cpp> <table> <count> FILES <file>...): the same for a product's own data, keyed
# by file name, as hollow::<table>[] and hollow::<count> (the product declares them, with EmbeddedFile).
#
# This file is also the generator: cmake -DSKIN=<dir> -DOUT=<out.cpp> -P HollowEmbed.cmake, or with
# -DFILES=<a|b> -DTABLE=<name> -DCOUNT=<name> in place of SKIN.

# Hidden files and the ones file managers leave behind are not part of a skin.
macro(_hollow_skin_files var dir)
  file(GLOB_RECURSE ${var} ${ARGN} "${dir}/*")
  list(FILTER ${var} EXCLUDE REGEX "(^|/)(\\.[^/]*|Thumbs\\.db|desktop\\.ini)$")
  list(SORT ${var})
endmacro()

if(CMAKE_SCRIPT_MODE_FILE)
  set(files "")
  if(NOT TABLE)
    set(TABLE kSkinFiles)
    set(COUNT kSkinFileCount)
  endif()
  if(FILES)
    string(REPLACE "|" ";" files "${FILES}")
    set(SKIN "")
  elseif(IS_DIRECTORY "${SKIN}")
    _hollow_skin_files(files "${SKIN}" RELATIVE "${SKIN}")
  endif()
  set(tmp "${OUT}.tmp")
  file(WRITE "${tmp}" "// Generated by HollowEmbed.cmake from ${SKIN}; do not edit.\n#include \"embedded_skin.h\"\n\nnamespace {\n")
  set(table "")
  set(i 0)
  foreach(f IN LISTS files)
    # file(READ HEX) gives two hex digits per byte. Eight bytes per regex match keeps this at about a
    # second per MB; the last few bytes go one at a time.
    if(SKIN)
      file(READ "${SKIN}/${f}" hex HEX)
    else()
      file(READ "${f}" hex HEX)
      get_filename_component(f "${f}" NAME)
    endif()
    string(LENGTH "${hex}" n)
    math(EXPR size "${n} / 2")
    math(EXPR cut "${n} - ${n} % 16")
    string(SUBSTRING "${hex}" 0 ${cut} head)
    string(SUBSTRING "${hex}" ${cut} -1 tail)
    string(REGEX REPLACE "(..)(..)(..)(..)(..)(..)(..)(..)" "0x\\1,0x\\2,0x\\3,0x\\4,0x\\5,0x\\6,0x\\7,0x\\8,\n" head "${head}")
    string(REGEX REPLACE "(..)" "0x\\1," tail "${tail}")
    if(size EQUAL 0)
      set(tail "0")   # an array cannot be empty; the table still says 0 bytes
    endif()
    file(APPEND "${tmp}" "const unsigned char f${i}[] = {\n${head}${tail}};\n")
    string(APPEND table "    {\"${f}\", f${i}, ${size}},\n")
    math(EXPR i "${i} + 1")
  endforeach()
  if(i EQUAL 0)
    set(table "    {\"\", nullptr, 0},\n")
  endif()
  file(APPEND "${tmp}" "} // namespace\n\nnamespace hollow {\nextern const EmbeddedFile ${TABLE}[];\nextern const size_t ${COUNT};\nconst EmbeddedFile ${TABLE}[] = {\n${table}};\nconst size_t ${COUNT} = ${i};\n} // namespace hollow\n")
  file(RENAME "${tmp}" "${OUT}")
  return()
endif()

function(hollow_embed_skin skin out)
  set(files "")
  if(skin)
    _hollow_skin_files(files "${skin}" CONFIGURE_DEPENDS)
  endif()
  add_custom_command(OUTPUT "${out}"
    COMMAND "${CMAKE_COMMAND}" "-DSKIN=${skin}" "-DOUT=${out}" -P "${CMAKE_CURRENT_FUNCTION_LIST_FILE}"
    DEPENDS ${files} "${CMAKE_CURRENT_FUNCTION_LIST_FILE}"
    COMMENT "Embedding skin ${skin}"
    VERBATIM)
endfunction()

function(hollow_embed_files out table count)
  cmake_parse_arguments(E "" "" "FILES" ${ARGN})
  string(REPLACE ";" "|" list "${E_FILES}")
  add_custom_command(OUTPUT "${out}"
    COMMAND "${CMAKE_COMMAND}" "-DFILES=${list}" "-DTABLE=${table}" "-DCOUNT=${count}" "-DOUT=${out}" -P "${CMAKE_CURRENT_FUNCTION_LIST_FILE}"
    DEPENDS ${E_FILES} "${CMAKE_CURRENT_FUNCTION_LIST_FILE}"
    COMMENT "Embedding ${table}"
    VERBATIM)
endfunction()
